INSERT INTO `room_types` (`created_by`, `created_date`, `modified_by`, `modified_date`, `base_price`, `included_services`, `surge_fee_afteraweek`, `surge_fee_beforeaweek`, `surge_fee_current_day`, `surge_fee_ongoing_week`, `type`, `view`, `weekend_surge_fee`, `description`, `image`)
VALUES
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '140', '1,3,4', '50', '0', '25', '10', 'Superior Room', 'Sea', '15', 'Enjoy breathtaking views of the sea in our Superior Room Sea View. These rooms combine comfort and elegance, providing a serene retreat with a stunning ocean backdrop. Immerse yourself in a world of tranquility where the sound of the waves becomes your lullaby.', 'SuperiorRoomSeaView.jpg'),
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '135', '1,3,4', '50', '0', '25', '10', 'Superior Room', 'Garden View', '15', 'Immerse yourself in tranquility with our Superior Room Garden View. Surrounded by lush greenery, these rooms offer a peaceful escape while maintaining a touch of sophistication. Revel in the beauty of nature as you unwind in the heart of our picturesque garden.', 'SuperiorRoomGardenView.jpg'),
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '190', '1,3,4', '50', '0', '25', '10', 'Junior Suite', 'Sea View', '15', 'Experience luxury with added space in our Junior Suite Sea View. These suites feature a separate living area, ensuring a comfortable and stylish stay with panoramic views of the sea. Indulge in the allure of spacious living and the grandeur of sea panoramas.', 'JuniorSuiteSeaView.jpg'),
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '185', '1,3,4', '60', '0', '25', '10', 'Junior Suite', 'Garden View', '15', 'Indulge in the perfect blend of comfort and nature in our Junior Suite Garden View. These suites offer a spacious living area and picturesque garden views for a truly relaxing experience. Delight in the harmony of nature as you enjoy the expansive living space.', 'JuniorSuiteGardenView.jpg'),
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '220', '1,3,4', '60', '0', '35', '20', 'Executive Room', 'Sea View', '15', 'Elevate your stay with our Executive Room Sea View. Designed for discerning travelers, these rooms offer refined furnishings and unobstructed sea views, creating a sophisticated ambiance. Unwind in luxury and sophistication against the backdrop of uninterrupted sea vistas.', 'ExecutiveRoomSeaView.jpg'),
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '215', '1,3,4', '60', '0', '35', '20', 'Executive Room', 'Garden View', '15', 'Find a balance of luxury and nature in our Executive Room Garden View. These rooms provide an upscale experience with a private garden view, combining comfort and aesthetics seamlessly. Immerse yourself in the juxtaposition of luxury and nature, surrounded by your private garden oasis.', 'ExecutiveRoomGardenView.jpg'),
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '250', '1,3,4', '60', '0', '35', '20', 'Luxury Suite', 'Sea View', '15', 'Immerse yourself in opulence with our Luxury Suite Sea View. These suites redefine luxury living, featuring a spacious layout, premium amenities, and panoramic sea views for an unforgettable stay. Experience the pinnacle of indulgence with expansive spaces and uninterrupted sea panoramas.', 'LuxurySuiteSeaView.jpg'),
    ('1', CURRENT_DATE, '1', CURRENT_DATE, '240', '1,3,4', '60', '0', '35', '20', 'Luxury Suite', 'Garden View', '15', 'Experience the epitome of luxury and serenity in our Luxury Suite Garden View. These suites offer an expansive living space, high-end amenities, and a private garden view, ensuring a truly indulgent retreat. Unwind in the lap of luxury, surrounded by the tranquility of your exclusive garden view sanctuary.', 'LuxurySuiteGardenView.jpg    ');